# Generated by Django 3.0.6 on 2020-05-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationApp', '0002_video_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(upload_to='media/', verbose_name='Video File'),
        ),
    ]
