# Generated by Django 3.0.6 on 2020-05-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationApp', '0003_auto_20200527_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.TextField(null=True, verbose_name='File Path'),
        ),
    ]
