# Generated by Django 3.0.6 on 2020-05-30 09:49

from django.db import migrations, models
import recommendationApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationApp', '0007_auto_20200527_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(upload_to=recommendationApp.models.changeFileName, verbose_name='Video File'),
        ),
    ]
