# Generated by Django 3.0.6 on 2020-05-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationApp', '0009_auto_20200530_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Video description'),
        ),
    ]
